module.exports = {
	"0": 'Tea core not init',
	"1": 'not supported',
	"2": "max loop",
	"3": "Node Object parent is circular",
	"1000": "Syntax Error",
	"1001": 'nonsupport, so sorry',
	"1002": 'The %s declaration statement need at class inward',
	"1003": 'Identifier "%s" is an const declaration, cant modify',
	"1004": 'Source index pair cant file "%s" token',
	"1005": 'class expression need a name',
	"1006": 'keyword cant do name',
	"1007": 'Var declaration syntax error',
	"1009": 'Let declaration syntax error',
	"1010": 'Const declaration syntax error',
	"1011": 'Export declaration syntax error',
	"1012": 'If statement syntax error',
	"1013": 'While statement syntax error',
	"1014": 'With statement syntax error',
	"1015": 'Do while statement syntax error',
	"1016": 'Try while statement syntax error',
	"1017": 'Switch while statement syntax error',
	"1018": 'For statement syntax error',
	"1019": 'Else statement syntax error',
	"1020": 'Case or default statement syntax error',
	"1021": 'extends statement syntax error',
	"1022": 'Condition expression of for statement syntax error',
	"1023": 'Condition expression miss right ")" token',
	"1024": 'Function declaration need a name',
	"1100": 'Unexpected statement',
	"1101": 'Unexpected statement end',
	"1102": '%s statement syntax error',
	"1103": 'Export statement params type error',
	"1104": 'Params expression miss right ")" token',
	"1105": 'Wrong token "%s" for block statement',
	"1106": 'Invalid block of statement',
	"1107": 'Invalid right-hand side in Assign expression',
	"1108": 'Unexpected Access expression',
	"1109": 'Invalid right token "]" in Access expression',
	"1110": 'Invalid right token "}" in Block statement',
	"1111": 'Unexpected token "%s"',
	"1112": 'Static methods error',
	"1113": 'Getter methods error',
	"1114": 'Setter methods error',
	"1115": 'Super statement error',
	"1116": 'Prototype methods error',
	"1117": 'Property methods error',
	"1118": 'Unexpected token',
	"1119": '"#!" symbole must side in the first line of the source',
	"1120": 'Illegal string template expression',
	"1121": 'ES5 standard dont supported',
	"1122": '',
	"1123": 'Json expression miss right "}" token!',
	"1124": 'Array expression miss right "]" token!',
	"1125": 'Unexpected comma token',
	"1126": 'Unexpected compel expression',
	"1127": 'Invalid right-hand side in selete expression',
	"2000": 'Pre-Process error',
	"2001": 'Include Processor Cannot find file "%s"',
	"2002": 'Unexpected tag of control pre-process',
	"2003": 'Replace loop in macro "%s"',
	"2004": "#script runing error: %s",
	"4000": 'Grammar Module Error',
	"4001": 'Unexpected syntax parser "%s"',
	"4002": 'Unexpected parser "%s" in "%s" syntax pattern object',
	"4003": 'Grammar pattern has nested loop',
	"5000": 'Standard Module Error',
	"5001": 'Substandard parse node name "%s"',
	"5002": 'Standard Module not has "%s" method',
	"5003": 'Undefined Standard parser "%s"',
	"5004": 'Standard Card object cant add a "%s" type object \n\n<stack>',
	"5005": 'Undefined Standard cache name "%s"',
	"5006": 'Invalid standard logic pattern "%s"',
	"5007": 'Undefined standard "%s"',
	"ASSIGN": "Invalid left-hand side in assignment"};