module.exports = {
	"0": 'tea core not init',
	"1": 'not supported',
	"2": "max loop",
	"3": "node object parent is circular",
	"1000": "Syntax Error",
	"1001": 'nonsupport, so sorry',
	"1002": 'the %s declaration statement need at class inward',
	"1003": 'identifier "%s" is an const declaration, cant modify',
	"1004": 'source index pair cant file "%s" token',
	"1005": 'class expression need a name',
	"1006": 'keyword cant do name',
	"1007": 'var declaration syntax error',
	"1009": 'let declaration syntax error',
	"1010": 'const declaration syntax error',
	"1011": 'export declaration syntax error',
	"1012": 'if statement syntax error',
	"1013": 'while statement syntax error',
	"1014": 'with statement syntax error',
	"1015": 'do while statement syntax error',
	"1016": 'try while statement syntax error',
	"1017": 'switch while statement syntax error',
	"1018": 'for statement syntax error',
	"1019": 'else statement syntax error',
	"1020": 'case or default statement syntax error',
	"1021": 'extends statement syntax error',
	"1022": 'invalid condition expression of "for" statement',
	"1023": 'condition expression miss right ")" token',
	"1024": 'need a name of function declaration ',
	"1025": 'unexpected argument of function declaration ',
	"1100": 'Unexpected statement',
	"1101": 'Unexpected token',
	"1102": '%s statement syntax error',
	"1103": 'export statement params type error',
	"1104": 'params expression miss right ")" token',
	"1105": 'wrong token "%s" for block statement',
	"1106": 'invalid block of statement',
	"1107": 'invalid right-hand side in assign expression',
	"1108": 'unexpected access expression',
	"1109": 'invalid right token "]" in access expression',
	"1110": 'invalid right token "}" in block statement',
	"1111": 'unexpected token (block expression error)',
	"1112": 'static methods error',
	"1113": 'getter methods error',
	"1114": 'setter methods error',
	"1115": 'invalid super expression',
	"1116": 'invalid spread expression',
	"1117": '%s expression cant include spread expression',
	"1118": 'unexpected token (comment expression error)',
	"1119": '"#!" symbole must side in the first line of the source',
	"1120": 'illegal string template expression',
	"1121": 'es5 standard dont supported',
	"1122": 'json expression error',
	"1123": 'json expression miss right "}" token!',
	"1124": 'array expression miss right "]" token!',
	"1125": 'unexpected comma token',
	"1126": 'unexpected grouping expression',
	"1127": 'invalid right-hand side in selete expression',
	"1128": 'invalid left-hand side expression in prefix operation',
	"1129": 'invalid left-hand side expression in postfix operation',
	"1130": 'invalid left-hand side in assignment',
	"1131": 'invalid rest expression',
	"1132": 'invalid array destructuring',
	"1133": 'invalid json destructuring',
	"1134": 'invalid import declaration',
	"2000": 'Pre-Process Error',
	"2001": 'cant include file "%s"',
	"2002": 'unexpected tag of control pre-process',
	"2003": 'replace loop in macro "%s"',
	"2004": "#script runing error: %s",
	"2005": 'define token pattern error',
	"2006": 'define include pattern error',
	"2007": 'define include is self',
	"2008": 'define argv error',
	"2009": 'define macro error',
	"2010": 'undefine macro error',
	"2011": 'define %s error',
	"2012": 'pre-process error',
	"2013": 'pre-process control "%s" error: %s',
	"2014": 'pre-process script run error: %s',
	"2015": 'undefined pre-process tag',
	"4000": 'Grammar Error',
	"4001": 'unexpected syntax parser "%s"',
	"4002": 'unexpected parser "%s" in "%s" syntax pattern object',
	"4003": 'grammar pattern has nested loop',
	"5000": 'Standard Error',
	"5001": 'substandard parse node name "%s"',
	"5002": 'standard module not has "%s" method',
	"5003": 'undefined standard parser "%s"',
	"5004": 'standard card object cant add a "%s" type object \n\n<stack>',
	"5005": 'undefined standard cache name "%s"',
	"5006": 'invalid standard logic pattern "%s"',
	"5007": 'undefined standard "%s"',
	"5008": "invalid standard pattern\n\"%s\"",
	"Assign": "invalid left-hand side in assignment"};