<?xml version='1.0' encoding='UTF-8'?> 
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version='1.0'>
  <dict>
    <key>repository</key>
    <dict>
      <key>tea</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>//.*?$|#!.*?$</string>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
          </dict>
          <dict>
            <key>match</key>
            <string>#!.*?$</string>
            <key>name</key>
            <string>comment.line.number-sign.js</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block</string>
            <key>begin</key>
            <string>\/\*</string>
            <key>end</key>
            <string>\*\/</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\&apos;{3}(?!&apos;)|\&quot;{3}(?!&quot;)|`</string>
            <key>name</key>
            <string>storage.type.template</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.js</string>
            <key>begin</key>
            <string>&apos;{4}|&apos;</string>
            <key>end</key>
            <string>&apos;{4}|&apos;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
                <key>name</key>
                <string>constant.character.escape.js</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.js</string>
            <key>begin</key>
            <string>&quot;{4}|&quot;</string>
            <key>end</key>
            <string>&quot;{4}|&quot;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
                <key>name</key>
                <string>constant.character.escape.js</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$\{((?:\{.*?\}|[^\{\}])+)\}|\$(\w+)</string>
                <key>name</key>
                <string>constant.character.escape.js</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.regexp.js</string>
            <key>begin</key>
            <string>(?&lt;=^|[=(:,|&amp;!]|return|if|else|while|switch|not)\s*/(?![/*+{}?])</string>
            <key>end</key>
            <string>\/[igm]*</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\\.)|\[((?:\\]|.)*?)\]</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>constant.character.escape</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>constant.character.escape</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>([\^$?*+|.])</string>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![a-zA-Z])(0[xX][0-9a-fA-F]+|(?:\.\d+|\d+(?:\.\d+)?)(?:e\-?\d+)?)</string>
            <key>name</key>
            <string>constant.numeric</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.(length|__proto__|prototype|constructor|call|apply|toString|replace|exports|split|keys|slice|splice|push|pop|shift|unshift)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other</string>
            <key>begin</key>
            <string>(?&lt;!return|var|let|const)(?&lt;=\w|\]\))\s*\[\s*(?![&apos;&quot;])</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\w+</string>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(function|export default|export|get|set|static|prototype|property) +([$\w]+) *\((.*?)\)(?=\s*[:{])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*([$\w]+)(?&lt;!if|else|while|with|switch|try|catch|finally) *\((.*?)\)(?=\s*[:{])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(function) *\(([^()]*)\)(?=\s*[:{])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\(([^()]*)\) *=&gt;</string>
            <key>name</key>
            <string>entity.name.function</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(class) +((?!extends\b)[$\w]+)( +extends +(,?[$\w]+))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(true|false|null|Infinity|NaN|undefined|global|void|exports|module)\b</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(for|goto|if|else|return|switch|case|default|try|catch|finally|throw|while|with|do|break|continue|delete|debugger|yield|import|require)\b</string>
            <key>name</key>
            <string>keyword.control</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(as|in|of|not is|not|is|and|or|typeof|new|instanceof|extends)\b</string>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(var|let|const|class|function|constructor|export|prototype|property|static|get|set)\b</string>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(eval|super|Array|Number|Function|Object)\b</string>
            <key>name</key>
            <string>support.function</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(this|JSON|console|Math|parseInt|parseFloat)\b</string>
            <key>name</key>
            <string>support.function</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:(__[\$a-zA-Z_]\w*)|([A-Z][\$a-zA-Z_]\w*))\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.character</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?&lt;!\))\s*\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(&quot;[^&quot;]+&quot;|\w+|\d+)\s*(?=\:)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#tea</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\(\s*\)</string>
            <key>name</key>
            <string>comment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\:{2}|\.{2})</string>
            <key>name</key>
            <string>storage</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([&lt;&gt;?\|][=-]+|[=-]+[&lt;&gt;?\|])</string>
            <key>name</key>
            <string>keyword.other</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^\w\s&quot;&apos;#{};,\.\[\]():])</string>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([\$a-zA-Z_]\w*) +(?!as|in|of|not is|not|is|and|or|instanceof)(?=[\w&quot;&apos;]|[-+][\$w(])</string>
            <key>name</key>
            <string>entity.name.tag</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>(^|(?&lt;=[:=,(]))\s*&lt;</string>
            <key>end</key>
            <string>(?&lt;!=)&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#syntax_pattern</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\&gt;</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>syntax_pattern</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\@(\@\=|\@|\=|\?|\~|\:|\!)\w+</string>
            <key>name</key>
            <string>comment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+\?|\*?|\?\:|\?\!|\?\=|\?|\+|\*|\!|∆\w+|∅|→|\\n\b|\&amp;(==|===|\!=|\!==))</string>
            <key>name</key>
            <string>string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#syntax_set</string>
          </dict>
          <dict>
            <key>match</key>
            <string>#[A-Z]\w+</string>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[A-Z]\w+</string>
            <key>name</key>
            <string>storage.type</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\w+|\\.|[^\{\}\(\)\[\]\#\|\,]|[\{\}\,\#\|](?=\s*[→∅?+*!∆]))</string>
            <key>name</key>
            <string>constant.character</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#syntax_sub_1</string>
          </dict>
        </array>
      </dict>
      <key>syntax_sub_1</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#syntax_sub_2</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#syntax_pattern</string>
          </dict>
        </array>
      </dict>
      <key>syntax_sub_2</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)\(</string>
        <key>end</key>
        <string>(?&lt;!\\)\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#syntax_pattern</string>
          </dict>
        </array>
      </dict>
      <key>syntax_set</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)\[</string>
        <key>end</key>
        <string>(?&lt;!\\)\]</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#syntax_pattern</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#tea</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>#(include)</string>
        <key>end</key>
        <string>;|(?&lt;!,)\n</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:(?:[^,;\s\\]+(?:\\ )*)+)</string>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </array>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>#(script|endif|end|ifdef|if|elifdef|elif|else)</string>
        <key>name</key>
        <string>keyword.other</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>#(sugar|expr|stam)</string>
        <key>end</key>
        <string>\n</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>(?&lt;!=)&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#syntax_pattern</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\\&gt;</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tea</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>#(token)\ +([\$a-zA-Z_]\w*(?:\s*,\s*[\$a-zA-Z_]\w*)*)|#(exp|stat)\ +([\$a-zA-Z_]\w*)\ +(\/[^\/]+\/)|#(define)\ +([\$a-zA-Z_]\w*)(?:\(((?:\(.*?\)|[^\)]*)*)\))?|#(test|end\w*)(.*$)|#(run|endrun|line|token|define|exp|stat|argv|undef|if\w*|el\w+)\b|#(include)\s*((?:(?:[^,;\s\\]+(?:\\ )*)+)(?:\s*,\s*(?:(?:[^,;\s\\]+(?:\\ )*)+))*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>comment</string>
          </dict>
          <key>11</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>12</key>
          <dict>
            <key>name</key>
            <string>keyword.prep</string>
          </dict>
          <key>13</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>#\w+</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
    </array>
    <key>fileTypes</key>
    <array>
      <string>tea</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!/usr/bin/env node</string>
    <key>foldingStartMarker</key>
    <string></string>
    <key>foldingStopMarker</key>
    <string></string>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>uuid</key>
    <string>93E017CC-6F27-11D9-90EB-000D93589AF6</string>
    <key>comment</key>
    <string>TeaJS Syntax: version 0.1</string>
    <key>name</key>
    <string>TeaJS</string>
    <key>scopeName</key>
    <string>source.js</string>
  </dict>
</plist>
